services:
  yt-downloader:
    build: .
    container_name: yt-downloader
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
      - DELETE_FILE_ON_TRASHCAN=true
    ports:
      - "8081:8081"  # Optional, expose if needed
