services:
  custom_metube:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    volumes:
      - /your/real/downloads/path:/downloads
      - /your/real/cookies/path:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
